version: 2.1
orbs: 
  swissknife: roopakv/swissknife@0.66.0
workflows:
  codeql: # Vulnerabilities check.
    jobs:
      - swissknife/codeql-analysis:
          name: "CodeQL Scan"
jobs:
  build:
    docker:
      - image: nodejs:latest
    parallelism: 4
    steps:
      - checkout
      - run: npm install -g eslint
      - run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ./bin
      - run: eslint ./... 2>&1 | ./bin/reviewdog -reporter=github-pr-review