version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: curl -L -O https://github.com/github/codeql-cli-binaries/releases/download/v2.8.2/codeql-linux64.zip
      - run: unzip codeql-linux64.zip -d .codeql
      - run: git clone $TESTSUIT_REPOS .ql-git
      - run: .codeql/codeql/codeql database analyze .ql-git/javascript/jscdb .ql-git/javascript/ql/src/codeql-suites/javascript-lgtm-full.qls --format=sarif-latest --output=query-results.sarif --download --threads=0 --additional-packs .codeql/
      - run: .codeql/codeql/codeql github upload-results --sarif="query-results.sarif" -g="https://github.com/BenCinn/Node-Server/" -r="BenCinn/Node-Server" -f="$(cat .git/HEAD | cut -d' ' -f2-)"
      - run: set +o pipefail
      - run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin
      - run: export CI_PULL_REQUEST="$CIRCLE_PR_NUMBER"; export CI_COMMIT="$CIRCLE_SHA1"; export CI_REPO_OWNER="BenCinn"; export CI_REPO_NAME="Node-Server"; export CI_BRANCH="$CIRCLE_BRANCH"
      - run: eslint . | ./bin/reviewdog -f=eslint -reporter=github-pr-review
