version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm install -g eslint # reviewdog
      - run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ./bin
      - run: touch .reviewdog.yml
      - run: eslint ./... 2>&1 | ./bin/reviewdog -reporter=github-pr-check