version: 2.1
orbs:
  node: circleci/node@4.3
  gh: circleci/github-cli@1.0
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: curl -L -O https://github.com/github/codeql-cli-binaries/releases/download/v2.8.2/codeql-linux64.zip
      - run: unzip codeql-linux64.zip -d .codeql
      - run: git clone $TESTSUIT_REPOS .ql-git
      - run: .codeql/codeql/codeql database analyze .ql-git/javascript/jscdb .ql-git/javascript/ql/src/codeql-suites/javascript-lgtm-full.qls --format=sarif-latest --output=query-results.sarif --download --threads=0 --additional-packs .codeql/
      - run: .codeql/codeql/codeql github upload-results --sarif="query-results.sarif" -g="https://github.com/BenCinn/Node-Server/" -r="BenCinn/Node-Server" -f="$(cat .git/HEAD | cut -d' ' -f2-)"